server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: astro_user
    password: astro_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Flyway handles schema creation
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false # Avoid strict type coupling between microservices

# Custom JWT configuration properties
application:
  security:
    jwt:
      # 256-bit secret key for HMAC-SHA256
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250655368566D5971
      expiration: 86400000 # 24 Hours in milliseconds
      refresh-token:
        expiration: 604800000 # 7 Days in milliseconds

  kafka:
    topics:
      user-deleted: user-deleted-topic